version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 10
    commands:
      - cd ./front
      - npm install -g
      - npm install --save-dev @angular-devkit/build-angular
      - npm install -g @angular/cli
  build:
    commands:
      - ng build
artifacts:
  files:
    - "**/*"
  base-directory: "dist*"
